import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { RiArrowRightSLine } from 'react-icons/ri';
import { useAxios } from '../hooks/useAxios';
var move = 0

const options = {
  method: 'GET',
  headers: {
    'Accept': 'application/vnd.api+json',
    'Content-Type': 'application/vnd.api+json'
  }
};

export default function Home() {

  const { data } = useAxios('https://kitsu.io/api/edge/chapters?page%5Blimit%5D=10&page%5Boffset%5D=0', options)

  function changepage(change) {
    move = move + change;
    var r = document.querySelector(':root');
    r.style.setProperty('--curpage', `${move}vw`);
    console.log(data)
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainslider}>
        <div className={styles.changebuttons}>
          <button className={styles.changebutton} onClick={() => { changepage(100) }}> < RiArrowRightSLine /> </button>
          <button className={styles.changebutton} onClick={() => { changepage(-100) }}> < RiArrowRightSLine /></button>
        </div>
        <div className={styles.slider}>
          <div className={styles.slideblock}>
            <img src="https://cdn.black-clover.org/file/sugois/kaiju-no8/Chapter-64/02.jpg" alt="" />
          </div>
          <div className={styles.slideblock}>
            <img src="https://cdn.black-clover.org/file/sugois/kaiju-no8/Chapter-64/03.jpg" alt="" />
          </div>
          <div className={styles.slideblock}>
            <img src="https://cdn.black-clover.org/file/sugois/kaiju-no8/Chapter-64/04.jpg" alt="" />
          </div>
          <div className={styles.slideblock}>
            <img src="https://up.mangadudes.com/one-piece/1/one-piece-1668166-035ead69a42d400ce08c84bed16839c3.jpg" alt="" />
          </div>
          <div className={styles.slideblock}>
            <img src="https://up.mangadudes.com/one-piece/1/one-piece-1668167-d4399b21bca94d1a401d004021ccb8bb.jpg" alt="" />
          </div>
          <div className={styles.slideblock}>
            <img src="https://up.mangadudes.com/one-piece/1/one-piece-1668168-08abe93b576927e8db9ab20031db9816.jpg" alt="" />
          </div>
          <div className={styles.slideblock}>
            <img src="https://up.mangadudes.com/one-piece/1/one-piece-1668170-33a83b105cfc24c7a3810273c2d45ffc.jpg" alt="" />
          </div>
        </div>
      </div>
    </div>
  )
}
